"""
Documented qualitative evidence for codes 3, 4 and 7, twenty largest displacement
contexts. Encoded from the research note; every entry carries its source.

status values:
  documented      - a named source documents this cause producing displacement here
  abuse_only      - the abuse is documented but flight/displacement is NOT attributed
  none_found      - searched, nothing found. A finding, not a gap left blank.

`scale` is people affected where a source gives a figure, else None. Figures are
NOT comparable to IDMC counts and must never be summed with them - they come from
individual investigations with different scopes and periods.
"""

Q = {
"SDN": {
 3: dict(status="documented", scale=500000,
   summary="RSF and allied militias screened civilians by tribe at checkpoints in El Geneina; Masalit and other non-Arab groups expelled. UN FFM found a genocidal campaign against non-Arab communities after the fall of El Fasher.",
   quote="If you answered that you are Massalit, they would kill you immediately.",
   sources=[("HRW, The Massalit Will Not Come Home","https://www.hrw.org/report/2024/05/09/the-massalit-will-not-come-home/ethnic-cleansing-and-crimes-against-humanity-in"),
            ("OHCHR on El Fasher","https://www.ohchr.org/en/press-releases/2026/02/sudan-evidence-el-fasher-reveals-genocidal-campaign-targeting-non-arab")],
   example="At the checkpoint they asked what tribe we were. Because we are Masalit we could not stay in El Geneina, so we walked to Chad."),
 4: dict(status="documented", scale=None,
   summary="UN Fact-Finding Mission found systematic mass arbitrary detention by both SAF and RSF, on grounds including tribal affiliation and political views. Movement itself criminalised.",
   quote=None,
   sources=[("OHCHR, June 2026","https://www.ohchr.org/en/press-releases/2026/06/sudan-arbitrary-detention-torture-and-enforced-disappearances-fueling")],
   example="Soldiers took my brother from the house at night and we did not hear from him again. We were told we were next, so we left."),
 7: dict(status="documented", scale=50000,
   summary="Merowe Dam displaced over 50,000 small-scale farmers to desert resettlement sites; protests dispersed with live ammunition. Case admitted by the African Commission.",
   quote=None,
   sources=[("Forced Migration Review","https://www.fmreview.org/askouri/"),
            ("EIPR, African Commission admissibility","https://eipr.org/en/press/2016/03/%E2%80%9Csudan-dams%E2%80%9D-case-declared-admissible-african-commission-mass-forced-evictions")],
   example="When they built the big dam the water covered our farm on the river, and they moved us out to the desert where nothing grows.")},

"SYR": {
 3: dict(status="documented", scale=None,
   summary="Identity-based killings of Alawis across Latakia, Tartous and Hama in March 2025; at least 1,426 killed. Thousands fled to mountain villages and into Lebanon. Property-rights violations preventing Kurdish return in Afrin.",
   quote=None,
   sources=[("HRW, Are you Alawi?","https://www.hrw.org/report/2025/09/23/are-you-alawi/identity-based-killings-during-syrias-transition"),
            ("Amnesty on coastal massacres","https://www.amnesty.org/en/latest/news/2025/04/syria-coastal-massacres-of-alawite-civilians-must-be-investigated-as-war-crimes/")],
   example="In March men came to our village asking each person which sect they belonged to. Because we are Alawi we ran up into the mountains."),
 4: dict(status="documented", scale=None,
   summary="Mass arbitrary detention and torture at Saydnaya; punitive demolition of thousands of homes in seven opposition neighbourhoods; Law No. 10 of 2018 confiscating the property of those who had fled.",
   quote=None,
   sources=[("Amnesty, Saydnaya","https://www.amnesty.org/en/mde24-5415-2017-en/"),
            ("HRW, Razed to the Ground","https://www.hrw.org/report/2014/01/30/razed-ground/syrias-unlawful-neighborhood-demolitions-2012-2013"),
            ("HRW on Law No. 10","https://www.hrw.org/news/2018/05/29/qa-syrias-new-property-law")],
   example="The security branch arrested my son and we never learned where he was taken. We left before they came for the rest of us."),
 7: dict(status="documented", scale=None,
   summary="Decree 66 of 2012 authorised redevelopment of Basateen al-Razi into the Marota City luxury development; families lost homes without the promised compensation. Development project and political punishment are the same act.",
   quote=None,
   sources=[("The New Humanitarian investigation","https://www.thenewhumanitarian.org/investigations/2017/04/20/decree-66-blueprint-al-assad-s-reconstruction-syria")],
   example="The government said our neighbourhood would be rebuilt with towers. They bulldozed our house, we got nothing for it, and we had to find somewhere else.")},

"UKR": {
 3: dict(status="documented", scale=None,
   summary="Persecution of Crimean Tatars since 2014 - house searches, enforced disappearances, terrorism prosecutions, banning of the Mejlis. Separately, Roma driven from settlements by radical groups in government-controlled Ukraine.",
   quote=None,
   sources=[("HRW on Crimean Tatars","https://www.hrw.org/news/2017/11/14/crimea-persecution-crimean-tatars-intensifies"),
            ("OHCHR on Roma","https://www.ohchr.org/en/press-releases/2018/07/ukraine-act-now-stop-systematic-persecution-roma-minority-alarming-attacks")],
   example="They kept searching our houses and arresting Crimean Tatar men on invented charges. We did not want to wait our turn, so we moved to the mainland."),
 4: dict(status="documented", scale=550000,
   summary="Commission of Inquiry found the war crimes of forcible transfer and deportation. 550,000 properties in occupied Ukraine registered as 'ownerless'; owners must take Russian citizenship and appear in person to avoid confiscation.",
   quote=None,
   sources=[("OHCHR Commission of Inquiry","https://www.ohchr.org/en/press-releases/2025/10/russian-authorities-committed-crimes-against-humanity-targeting-civilian"),
            ("Bellingcat on Mariupol","https://www.bellingcat.com/news/europe/2025/11/14/building-on-ruins-the-russification-of-mariupol-one-apartment-block-at-a-time/")],
   example="They held my husband for weeks and beat him, and then told us to leave and go to the other side. They kept our documents."),
 7: dict(status="documented", scale=350000,
   summary="Chornobyl 1986: 116,000 evacuated immediately, approximately 350,000 relocated in total. Within the lifetime of any respondent over about 40 - directly relevant to a lifetime-recall question.",
   quote=None,
   sources=[("IAEA","https://www.iaea.org/newscenter/pressreleases/chernobyl-true-scale-accident")],
   example="After the reactor exploded they came with buses and told us the whole town had to leave and never come back.")},

"COL": {
 3: dict(status="documented", scale=None,
   summary="Constitutional Court Autos 004 and 005 of 2009 found displacement placed specific Indigenous and Afro-descendant peoples at risk of extinction. The Special Jurisdiction for Peace accepted jurisdiction over persecution on grounds of sexual orientation and gender identity as a crime against humanity - the only such finding among the twenty countries.",
   quote=None,
   sources=[("JEP Macro Case 005 analysis","https://www.ejiltalk.org/gender-based-persecution-as-a-crime-against-humanity-a-milestone-for-lgbti-rights-before-the-colombian-special-jurisdiction-for-peace/"),
            ("UNHCR on Indigenous displacement","https://www.acnur.org/fileadmin/Documentos/RefugiadosAmericas/Colombia/EN/Indigenous_people_and_forced_displacement_in_Colombia.pdf")],
   example="They put up a list of names of gay and trans people and said we had three days to leave the neighbourhood."),
 4: dict(status="documented", scale=None,
   summary="JEP convicted 12 former army members for 135 enforced disappearances and extrajudicial killings. State security forces named among perpetrators in Macro Case 005. Aerial glyphosate fumigation destroying subsistence crops.",
   quote=None,
   sources=[("HRW World Report 2026","https://www.hrw.org/world-report/2026/country-chapters/colombia")],
   example="The army came into the neighbourhood and my nephew was taken away and never came back. We could not stay after that."),
 7: dict(status="documented", scale=None,
   summary="Tabaco destroyed for Cerrejón coal expansion in 2001 - community isolated, then evicted; no resettlement completed by 2022. El Quimbo dam evicted ~100 families. Hidroituango opponents killed and displaced.",
   quote=None,
   sources=[("London Mining Network on Tabaco","https://londonminingnetwork.org/2022/08/21-years-since-eviction-of-the-tabaco-community-in-colombia-and-still-no-justice/"),
            ("International Rivers on El Quimbo","https://www.internationalrivers.org/news/a-victory-after-15-years-land-restitution-for-families-displaced-by-the-el-quimbo-dam/")],
   example="The mine kept growing until they took our village. They cut the water and the electricity, knocked down the houses, and we had to go.")},

"COD": {
 3: dict(status="documented", scale=None,
   summary="Congolese Tutsi and Banyamulenge attacked by Wazalendo militias; CODECO attacks on Hema displacement camps in Ituri; ADF massacre of Christians at a church in Komanda. UN reporting does not disaggregate victims by ethnicity - the evidence is from HRW and journalism.",
   quote=None,
   sources=[("HRW World Report 2026","https://www.hrw.org/world-report/2026/country-chapters/democratic-republic-of-congo"),
            ("HRW on Ituri camp raid","https://www.hrw.org/news/2023/07/24/dr-congo-deadly-militia-raid-ituris-displaced")],
   example="People in the market started saying we were not really Congolese because of our tribe. Then our cattle were taken and our uncle was killed."),
 4: dict(status="documented", scale=None,
   summary="M23 and Rwandan forces forcibly recruited and detained thousands; hundreds died in detention camps. M23 ordered camp evacuations on 72 hours' notice. Note M23 is a de facto authority, not a recognised state.",
   quote=None,
   sources=[("HRW on M23 detention","https://www.hrw.org/news/2026/06/10/dr-congo-rwanda-m23-forcibly-recruit-detain-thousands"),
            ("Amnesty on M23 detention sites","https://www.amnesty.org/en/latest/news/2025/05/drc-m23-kill-torture-and-hold-civilians-hostage-at-detention-sites-new-investigation/")],
   example="The men who control our area now stopped my son at a checkpoint and took him away for training. We left so they would not take the younger one too."),
 7: dict(status="documented", scale=39000,
   summary="Forced evictions at four industrial cobalt and copper sites in Lualaba and Haut-Katanga, including ~39,000 residents of Cité Gécamines at the COMMUS mine, homes marked with red crosses. 3,500-6,500 more at risk from the Lobito Corridor railway.",
   quote=None,
   sources=[("Amnesty on cobalt mining evictions","https://www.amnesty.org/en/latest/news/2023/09/drc-cobalt-and-copper-mining-for-batteries-leading-to-human-rights-abuses/"),
            ("Global Witness on Lobito Corridor","https://globalwitness.org/en/campaigns/transition-minerals/thousands-in-drc-could-face-eviction-from-lobito-corridor-railway/")],
   example="The mining company said the land now belonged to them. They put marks on the houses and brought machines.")},

"AFG": {
 3: dict(status="documented", scale=2800,
   summary="Taliban forcibly evicted Hazara families across five provinces with notice as short as three days; at least 2,800 evicted in Daikundi and Uruzgan alone. ISKP has killed and injured 700+ Hazaras since 2021. LGBT Afghans documented fleeing after gang rape, mob violence and Taliban threats.",
   quote="Even if you go to the skies, we'll find you.",
   sources=[("HRW on Hazara evictions","https://www.hrw.org/news/2021/10/22/afghanistan-taliban-forcibly-evict-minority-shia"),
            ("HRW/Outright on LGBT Afghans","https://www.hrw.org/report/2022/01/26/even-if-you-go-skies-well-find-you/lgbt-people-afghanistan-after-taliban-takeover")],
   example="They told us this land was never ours, because of who we are and how we pray. We had three days. They would not even let us take the harvest."),
 4: dict(status="documented", scale=None,
   summary="UNAMA recorded at least 800 instances of extrajudicial killing, arbitrary detention, torture and enforced disappearance targeting former government affiliates, despite the declared amnesty. UNAMA does not quantify resulting flight.",
   quote=None,
   sources=[("UNAMA, Impunity Prevails","https://unama.unmissions.org/impunity-prevails-human-rights-violations-against-former-government-officials-and-armed-force")],
   example="My husband worked for the old government. Men came to the house asking for him twice. A cousin of ours was taken and his body was found later."),
 7: dict(status="documented", scale=6000,
   summary="Kabul Municipality cleared 1.5 million square metres across 15 of Kabul's 22 police districts, 2021-2024, verified by satellite imagery. Over a third of demolitions hit informal settlements housing IDPs and returnees; 80%+ of urban properties lack formal title, blocking compensation. One June 2024 demolition made 800 families homeless.",
   quote=None,
   sources=[("CIR Afghan Witness","https://www.info-res.org/afghan-witness/articles/documenting-demolitions-the-talibans-land-clearance-campaign-and-its-impact-on-marginalised-communities/"),
            ("NRC","https://www.nrc.no/news/2024/june/afghan-evictions")],
   example="The city officials came and said our houses were built on land that was not ours. The machines knocked everything down. We had no papers so we got nothing.")},

"MMR": {
 3: dict(status="documented", scale=750000,
   summary="UN Fact-Finding Mission concluded the 2016-17 Rakhine operations warranted prosecution for genocide; roughly 750,000 Rohingya driven to Bangladesh. New atrocities from 2024 by both the military and the Arakan Army; ~630,000 Rohingya remain under what HRW calls an apartheid system. The 1982 Citizenship Law is the legal architecture - respondents may describe this as denial of nationality rather than ethnicity.",
   quote=None,
   sources=[("OHCHR on genocide finding","https://www.ohchr.org/en/press-releases/2019/09/myanmars-rohingya-persecuted-living-under-threat-genocide-un-experts-say"),
            ("HRW on 2024 atrocities","https://www.hrw.org/news/2024/08/22/myanmar-new-atrocities-against-rohingya")],
   example="They burned our part of the town but not the other part. They said we do not belong in this country and we have no citizenship card."),
 4: dict(status="documented", scale=None,
   summary="Over 14,500 arrested and 2,000+ killed since the coup; torture, sexual violence against LGBTQI+ detainees, enforced disappearance. Nearly 800 properties seized including 278 homes of 274 NLD members - directly the 'confiscation of property' clause.",
   quote=None,
   sources=[("Amnesty on detention and torture","https://www.amnesty.org/en/latest/news/2022/08/myanmar-detainees-tortured-to-crush-opposition-to-coup/"),
            ("RFA on property seizures","https://www.rfa.org/english/news/myanmar/properties-11222022171501.html")],
   example="My nephew joined the protests. The soldiers came looking for him, and later they put a seal on the house and said it was taken."),
 7: dict(status="documented", scale=50000,
   summary="UN experts: over 50,000 people exposed to forced eviction and housing destruction in late 2022 alone - 40,000+ in Mingaladon, 5,000+ households in Mandalay overnight, residents given 30 minutes in Mayangone. Letpadaung copper mine and Myitsone dam displacement separately documented.",
   quote=None,
   sources=[("OHCHR on forced evictions","https://www.ohchr.org/en/press-releases/2022/12/myanmar-over-50000-exposed-forced-evictions-and-housing-destruction-say-un"),
            ("Amnesty on Letpadaung","https://www.amnesty.org/en/documents/asa16/1563/2015/en/")],
   example="The officials told our whole quarter to pull down our own houses within a few days - there was no other place given to us.")},

"YEM": {
 3: dict(status="documented", scale=None,
   summary="HRW documents a systematic Houthi effort to persecute Baha'is and force them into exile; six released in 2020 were forced abroad. Yemen's Jewish community effectively ended by expulsions in 2021. Christians and converts arbitrarily detained and disappeared.",
   quote=None,
   sources=[("HRW on Baha'is","https://www.hrw.org/news/2023/05/30/yemen-houthis-forcibly-disappear-bahais"),
            ("HRW on Christians","https://www.hrw.org/news/2026/02/09/yemen-houthis-arbitrarily-detain-disappear-christians")],
   example="They came to our gathering and took people away. Some of us were told to leave the country and never come back."),
 4: dict(status="documented", scale=None,
   summary="69 UN employees in Houthi detention as of December 2025, most denied family contact or legal representation, plus dozens of journalists. All warring parties have arbitrarily detained and tortured. UN monitoring mechanism ended in 2021 leaving virtually no accountability.",
   quote=None,
   sources=[("HRW World Report 2026","https://www.hrw.org/world-report/2026/country-chapters/yemen")],
   example="They arrested my brother and we heard nothing for months. Then they came asking about the rest of us."),
 7: dict(status="documented", scale=461,
   summary="Distinctive: no dams or mines. Code 7 in Yemen means eviction from displacement sites as land values rise - 461 households evicted in Marib in six months, 179 people injured, 83% of affected sites on private land. A generic 'dam or road project' prompt would produce a false zero here.",
   quote=None,
   sources=[("NRC forced eviction analysis","https://www.nrc.no/resources/reports/forced-eviction-analysis-in-managed-idp-sites-a-focus-on-marib-governorates")],
   example="The owner said the land was worth money now. They came with machines and pulled down our shelter - some people were hurt trying to stop them.")},

"SOM": {
 3: dict(status="documented", scale=None,
   summary="The code 3 signal here is clan and minority-caste status, not ethnicity as a European drafter would frame it. Rahanweyn and Somali Bantu displaced people face systematic discrimination; camp gatekeepers replace displaced families with their own clan. No documented displacement on religious, national or SOGI grounds found.",
   quote="You are from Bay and Bakool regions. You are al-Shabaab's people. You are not displaced by drought, you are cursed people.",
   sources=[("HRW, Hostages of the Gatekeepers","https://www.hrw.org/report/2013/03/28/hostages-gatekeepers/abuses-against-internally-displaced-mogadishu-somalia"),
            ("NRC on minority HLP rights","https://www.nrc.no/resources/reports/community-driven-consultations-on-hlp-needs-among-minority-marginalised-displaced-communities-in-mogadishu")],
   example="We are from a small family group with no gunmen of our own. A stronger group took our farm and said people like us have no right to be here."),
 4: dict(status="documented", scale=None,
   summary="Government forces evicting camps without warning; displaced men who complained to the district commissioner were arrested and detained. UN estimated 13% of all Mogadishu displacement resulted from government- and landlord-ordered evictions.",
   quote="My home was destroyed by the commissioner of Hodan district. He destroyed my house with his bulldozer.",
   sources=[("HRW, Hostages of the Gatekeepers","https://www.hrw.org/report/2013/03/28/hostages-gatekeepers/abuses-against-internally-displaced-mogadishu-somalia")],
   example="Soldiers said my son was with the fighters and took him away. We were afraid they would come back for the rest of us."),
 7: dict(status="documented", scale=1500000,
   summary="THE LARGEST DOCUMENTED CODE 7 CASE ANYWHERE. Forced evictions affected more than 1.5 million people in informal settlements 2018-2024, over 80% in Mogadishu; 100,907 evicted in Mogadishu in 2023 alone. 87% of Mogadishu's displaced lack clear tenure. Driven by a construction boom and land grabs by political and military elites.",
   quote=None,
   sources=[("NRC","https://www.nrc.no/resources/reports/community-driven-consultations-on-hlp-needs-among-minority-marginalised-displaced-communities-in-mogadishu"),
            ("EUAA country guidance","https://euaa.europa.eu/country-guidance-somalia-2023/424-forced-evictions"),
            ("The New Humanitarian","https://www.thenewhumanitarian.org/feature/2024/09/11/somalia-mogadishu-skyline-transforms-urban-poor-call-economic-inclusion")],
   example="The people who claim the land came early in the morning with tractors and pulled down our shelter to build apartments. They gave us no notice.")},

"NGA": {
 3: dict(status="documented", scale=None,
   summary="HRW found victims in Plateau and Kaduna 'targeted and killed based simply on their ethnic or religious identity', with displacement running in BOTH directions - Muslim and Christian communities each emptied from specific villages. The 'Christian genocide' framing is disputed by ICG, HRW and EUAA; attribute rather than assert.",
   quote="Why should you come here and settle? Why should you not stay in your [own] places?",
   sources=[("HRW, Leave Everything to God","https://www.hrw.org/report/2013/12/12/leave-everything-god/accountability-inter-communal-violence-plateau-and-kaduna")],
   example="After the killings, people of the other religion in our village told us we did not belong there and burned our houses."),
 4: dict(status="documented", scale=200000,
   summary="Military arbitrarily arrested over 20,000 since 2011; ~7,000 detainees died in custody. Separately, Borno State closed 10 IDP camps affecting over 200,000 displaced people, using dawn raids, 10-15 day deadlines and abrupt termination of food aid - authorities forcing displaced people to move again.",
   quote=None,
   sources=[("Amnesty on Giwa Barracks","https://www.amnesty.org/en/latest/press-release/2016/03/nigeria-no-justice-for-the-640-men-and-boys-slain-by-military-following-giwa-barracks-attack-two-years-ago/"),
            ("HRW on camp shutdowns","https://www.hrw.org/report/2022/11/02/those-who-returned-are-suffering/impact-camp-shutdowns-people-displaced-boko")],
   example="Soldiers came looking for the fighters and rounded up all the men, including my brother. He has been held for years and has never been to court."),
 7: dict(status="documented", scale=50000,
   summary="At least 50,000 forcibly evicted from Lagos informal settlements since 2013 - Otodo Gbame alone over 30,000. Police and military, bulldozers, arson, live ammunition; at least 11 died. Land became luxury estates. NOTE: Niger Delta oil pollution is extensively documented as harm to health and livelihoods but NOT as attributed displacement.",
   quote=None,
   sources=[("Amnesty, The Human Cost of a Megacity","https://www.amnestyusa.org/wp-content/uploads/2017/11/The-Human-Cost-of-a-Megacity-Nigeria-forced-evictions-report.pdf")],
   example="The government sent bulldozers and police to clear our waterfront settlement. They set the houses on fire and we lost everything.")},

"SSD": {
 3: dict(status="documented", scale=25000,
   summary="Government forces conducted house-to-house searches in Juba in December 2013 screening people by ethnicity; over 25,000 Nuer fled to UN bases. Small Arms Survey documents an organised attempt to force the Shilluk off the east bank of the White Nile - up to 80% of the Shilluk population displaced.",
   quote=None,
   sources=[("HRW on ethnic targeting","https://www.hrw.org/news/2014/01/16/south-sudan-ethnic-targeting-widespread-killings"),
            ("Small Arms Survey on the Shilluk","https://www.smallarmssurvey.org/sites/default/files/resources/HSBA-Report-South-Sudan-Shilluk.pdf")],
   example="Soldiers went house to house asking what language we spoke and where our people were from. They were taking away the men of our group, so we ran."),
 4: dict(status="documented", scale=None,
   summary="National Security Service detains critics without warrant authority. A journalist held nine months, beaten and waterboarded, then helped across the border - one of the few cases where a named source documents state abuse directly causing flight.",
   quote=None,
   sources=[("HRW, Silencing Dissent","https://www.hrw.org/news/2020/12/14/witness-silencing-dissent-south-sudan")],
   example="My relative wrote things about the government. Security men took him away and beat him for months. When they let him out they kept watching him, so he left the country."),
 7: dict(status="none_found", scale=None,
   summary="No documented large-scale dam, mining or infrastructure displacement found; the Jonglei Canal remains unbuilt. Oil-field contamination in Unity State is documented, but the Rift Valley Institute attributes the associated displacement primarily to flooding rather than pollution. Expect code 7 to be a very low-frequency response here.",
   quote=None,
   sources=[("Rift Valley Institute","https://riftvalley.net/publication/why-south-sudans-unity-state-is-drowning-in-pollution/")],
   example=None)},

"ETH": {
 3: dict(status="documented", scale=723000,
   summary="Systematic expulsion of Tigrayans from Western Tigray - 24-72 hour ultimatums, identity documents seized before people were allowed to cross the Tekeze, homes marked 'Amhara house', bans on speaking Tigrinya. 723,000 IDPs registered from Western Tigray by June 2021; 740,000 still displaced in April 2026. Ethnic Amhara separately targeted in western Oromia, with attribution contested.",
   quote="Tigrayans belong east of the Tekeze River.",
   sources=[("HRW/Amnesty, We Will Erase You from This Land","https://www.hrw.org/report/2022/04/06/we-will-erase-you-land/crimes-against-humanity-and-ethnic-cleansing-ethiopias"),
            ("HRW, April 2026","https://www.hrw.org/news/2026/04/22/ethiopia-persecution-of-tigrayans-unrelenting")],
   example="Officials told us our people do not belong on this side of the river. They gave us three days, took our identity papers, and put another family in our house."),
 4: dict(status="documented", scale=None,
   summary="Mass arbitrary arrests in Amhara in 2024; ethnic profiling in Addis Ababa with 1,000+ detained in a single week; detention facilities in Western Tigray with torture and starvation; systematic confiscation of livestock, crops, identity documents and homes.",
   quote=None,
   sources=[("HRW World Report 2025","https://www.hrw.org/world-report/2025/country-chapters/ethiopia"),
            ("UN News on Addis detentions","https://news.un.org/en/story/2021/11/1105892")],
   example="They were stopping people in the city and checking identity cards, and arresting men from our group. My husband was held for months without ever going to court."),
 7: dict(status="documented", scale=200000,
   summary="Gibe III dam and Kuraz sugar plantations threatened ~200,000 agro-pastoralists across eight indigenous communities in the Lower Omo, with forced land seizure, military intimidation and no compensation. The Corridor Development Project, launched 2022 and reportedly replicated in 58+ cities, evicted at least 872 people in Addis in November 2024 alone - none reported receiving any compensation.",
   quote=None,
   sources=[("HRW on the Lower Omo","https://www.hrw.org/report/2012/06/18/what-will-happen-if-hunger-comes/abuses-against-indigenous-peoples-ethiopias"),
            ("Amnesty on the Corridor Development Project","https://www.amnesty.org/en/documents/afr25/9021/2025/en/")],
   example="The government marked our neighbourhood for the new city project. They knocked the houses down and we were given nothing.")},

"BFA": {
 3: dict(status="documented", scale=None,
   summary="HRW concluded that ethnic targeting of Fulani communities by military forces and state-armed VDP militias, leading to the mass displacement of entire communities, amounts to ethnic cleansing. At Solenzo in March 2025 at least 130 Fulani civilians were killed and thousands fled towards Mali.",
   quote="They went into the bush to kill all the Fulani they saw, they wanted to exterminate us all.",
   sources=[("HRW Q&A, April 2026","https://www.hrw.org/news/2026/04/02/qa-war-crimes-crimes-against-humanity-by-all-sides-in-burkina-faso"),
            ("HRW on Solenzo","https://www.hrw.org/news/2025/05/12/burkina-faso-army-directs-ethnic-massacres")],
   example="Because we are Fulani, the militia said we were with the armed men. They came for the Fulani families in particular, so all of us left together."),
 4: dict(status="documented", scale=None,
   summary="Journalists and activists abducted and unlawfully conscripted into the army as reprisal for criticism; six judges and a lawyer forcibly disappeared in October 2025. Abuse well documented; resulting flight of individually-targeted critics not quantified.",
   quote=None,
   sources=[("HRW on conscripted journalists","https://www.hrw.org/news/2025/04/07/disappeared-burkina-faso-journalists-feared-unlawfully-conscripted"),
            ("HRW on disappeared judicial officers","https://www.hrw.org/news/2025/10/22/burkina-faso-judicial-officers-feared-forcibly-disappeared")],
   example="My brother was taken away by men who did not say who they were, and he never came back."),
 7: dict(status="documented", scale=None,
   summary="Fifteen industrial gold mines opened since 2007 with thousands of households relocated to new villages - Imiougou, Taparko, Karma, Essakane - compensated in cash rather than replacement land. Ouagadougou airport-area demolitions in 2025 and 2026 with officials stating no legal provision for compensation existed.",
   quote="They have taken everything from us: our land, our jobs, our health, our peace and our hope.",
   sources=[("ROAPE / GLOCON research","https://roape.net/2019/03/19/the-mines-make-us-poor-large-scale-mining-in-burkina-faso/")],
   example="The gold mining company took over our fields. They moved our whole village to a new site and gave us money instead of land.")},

"HTI": {
 3: dict(status="documented", scale=None,
   summary="Weak and unusual. The documented cases are targeting on ascribed belief and age - at least 110 elderly residents killed at Wharf Jérémie in December 2024 after a gang leader's vodou priest accused them of witchcraft - and on perceived community affiliation at Pont-Sondé. No ethnic, religious, national-origin or SOGI persecution found in the conventional sense.",
   quote=None,
   sources=[("ACLED on the Wharf Jérémie massacre","https://acleddata.com/brief/december-6-7-massacre-wharf-jeremie-haiti-expert-comment"),
            ("ACLED on Pont-Sondé","https://acleddata.com/brief/pont-sonde-massacre-marks-surge-gran-grifs-deadly-campaign-artibonite-acled-insight")],
   example="They said the old people in our area were doing witchcraft, and they started killing them. My mother is elderly so we took her away."),
 4: dict(status="documented", scale=None,
   summary="OHCHR recorded 5,519 killed between March 2025 and January 2026, of which 3,497 resulted from security force operations - more than double the 1,424 attributed to gangs. 247 instances of actual or attempted summary execution by police. Drone strikes by a government-hired private military company described as targeted killings. Displacement causation not attributed by the source.",
   quote=None,
   sources=[("OHCHR, March 2026","https://www.ohchr.org/en/press-releases/2026/03/gangs-expand-reach-haiti-amid-persistent-deadly-violence-un-human-rights")],
   example="During the police operation they were shooting at anyone in the street, not only the bandits. My neighbour was killed and we did not wait."),
 7: dict(status="documented", scale=400,
   summary="Largely historical. Forced evictions from post-earthquake displacement camps by landowners and authorities, 2010-2015; ~400 farming families displaced from 250 hectares for the Caracol Industrial Park.",
   quote=None,
   sources=[("Amnesty, Nowhere To Go","https://www.amnestyusa.org/reports/nowhere-to-go-forced-evictions-in-haitis-displacement-camps/"),
            ("Accountability Counsel on Caracol","https://www.accountabilitycounsel.org/client-case/haiti-caracol-industrial-park/")],
   example="The owner of the land where our camp was came with men and took down the shelters. They told us to go and gave us nothing.")},

"VEN": {
 3: dict(status="documented", scale=None,
   summary="Over 1,900 detained as political prisoners after the July 2024 election; the opposition presidential candidate was forced to flee. Pro-government colectivos marked ~30 houses with an X to identify opposition supporters. Indigenous Pemón and Warao dispossessed by illegal gold mining. SOGI evidence is thinner and largely press-sourced.",
   quote=None,
   sources=[("HRW World Report 2026","https://www.hrw.org/world-report/2026/country-chapters/venezuela"),
            ("OCCRP on house marking","https://www.occrp.org/en/news/maduro-opponents-in-venezuela-find-their-houses-marked-with-an-x")],
   example="My son voted for the opposition and worked at the polling table. They put a mark on our door, and we understood we had to go."),
 4: dict(status="documented", scale=5800,
   summary="UN Fact-Finding Mission found torture, sexual torture and enforced disappearance amounting to crimes against humanity. Operation Tun Tun conducted nighttime house-to-house arrests. In Apure in 2021, security forces executed, detained, tortured, looted and burned homes - over 5,800 people fled into Colombia, one of the clearest documented cases of state abuse directly causing cross-border displacement.",
   quote=None,
   sources=[("OHCHR Fact-Finding Mission","https://www.ohchr.org/en/press-releases/2025/03/venezuela-harsh-repression-and-crimes-against-humanity-ongoing-fact-finding"),
            ("HRW on Apure","https://www.hrw.org/news/2021/04/26/venezuela-security-force-abuses-colombia-border")],
   example="They came to the house at night without a warrant and took my cousin away. Nobody would tell us where he was. We left before they came back."),
 7: dict(status="documented", scale=None,
   summary="The Orinoco Mining Arc opened ~112,000 km2 to mining over indigenous territory, driving Pemón dispossession, mercury contamination and control of mining zones by armed criminal organisations. Because displacement is mediated by armed groups rather than a resettlement order, respondents may code it 1, 2 or 5 rather than 7.",
   quote=None,
   sources=[("InfoAmazonia","https://infoamazonia.org/en/2023/08/06/armed-groups-threaten-indigenous-lands-in-southern-venezuela/")],
   example="The miners came onto our land in the thousands. The river turned brown and the fish were not safe to eat, so our community moved.")},

"IRQ": {
 3: dict(status="documented", scale=None,
   summary="ISIS's 2014 campaign against Sinjar targeted Yazidis as an ethno-religious group - mass killing, enslavement, forced conversion - formally recognised as genocide. Christians of the Nineveh Plains given convert-pay-or-leave ultimatums. The 2024 law criminalising same-sex relations creates persecution risk; documented displacement from it is thin because the law is recent.",
   quote=None,
   sources=[("USCIRF on Sinjar","https://www.uscirf.gov/news-room/uscirf-spotlight/recovering-genocide-yazidis-return-sinjar"),
            ("HRW World Report 2026","https://www.hrw.org/world-report/2026/country-chapters/iraq")],
   example="They came for us because we are Yazidi. They took the women and killed the men, so everyone who could ran to the mountain."),
 4: dict(status="documented", scale=None,
   summary="Police, Federal Police, PMF and National Security Service seized homes of relatives of ISIS suspects; families could not reclaim property because security screening automatically failed them. Collective banishment of families from home areas. IMPORTANT: in Iraq code 4 is often about being PREVENTED FROM RETURNING rather than made to leave - which the stem 'have you ever left a home due to...' does not capture.",
   quote="If you don't leave now, we should break your legs.",
   sources=[("HRW on property confiscation","https://www.hrw.org/news/2018/04/19/iraq-isis-suspects-homes-confiscated"),
            ("HRW on banishment","https://www.hrw.org/news/2018/04/26/iraq-local-forces-banish-isis-suspects-families")],
   example="Because my brother's name was on a list, the security men took our house and would not let us back into the neighbourhood."),
 7: dict(status="documented", scale=100000,
   summary="The Makhoul Dam under construction on the Tigris will displace more than 100,000 people from 40 communities in Saladin and Kirkuk, many of whom had only recently returned from ISIS-era displacement. Gas flaring and Basra water salinisation separately documented - the latter straddling codes 6 and 7.",
   quote=None,
   sources=[("Save the Tigris on Makhoul Dam","https://savethetigris.org/press-release-save-the-tigris-launches-a-new-report-on-the-makhoul-dam/"),
            ("HRW on gas flaring","https://www.hrw.org/news/2023/05/03/iraq-gas-flaring-tied-cancer-surge")],
   example="They are building a dam and our village will be under the water. We were told to leave the land.")},

"CAF": {
 3: dict(status="documented", scale=50000,
   summary="Anti-balaka forced Muslims out of western CAR in early 2014. Yaloké had roughly 30,000 Muslims and eight mosques before the conflict; fewer than 500 Muslims and one mosque remained by February 2014. Roughly 50,000 Muslims were evacuated from Bangui by air. Nobody fled a battle - they were expelled for being Muslim.",
   quote="The Peuhl and any Muslim of Chadian descent have 24 hours to leave the city or face attack.",
   sources=[("HRW, Muslims Forced to Flee","https://www.hrw.org/news/2014/02/12/central-african-republic-muslims-forced-flee"),
            ("Minority Rights Group on the Mbororo","https://minorityrights.org/communities/mbororo/")],
   example="The militia said all Muslims had to be out of the town within one day or they would kill us. They burned the mosque, so my family left everything."),
 4: dict(status="documented", scale=None,
   summary="UN experts found Wagner personnel operating alongside CAR armed forces and police implicated in arbitrary detention, torture, disappearances and summary execution - and noted victims cannot obtain redress because the perpetrators operate jointly with state forces. Respondents may not know whether the men who took their relatives were 'authorities'.",
   quote=None,
   sources=[("UN experts on Wagner in CAR","https://reliefweb.int/report/central-african-republic/car-russian-wagner-group-harassing-and-intimidating-civilians-un")],
   example="Men in uniform came at night, took my brother away and we never saw him again."),
 7: dict(status="abuse_only", scale=None,
   summary="Gold-mining river pollution at Bozoum - residents of Boyélé reported skin irritation and had to walk 10 km for clean water - and expulsion of artisanal miners from sites taken by Wagner. But NO documented large-scale development-induced resettlement programme. Expect near-zero code 7 responses.",
   quote=None,
   sources=[("France 24 Observers","https://observers.france24.com/en/20190411-central-african-republic-river-chinese-mining-companies"),
            ("Amnesty AFR 19/2708/2020","https://www.amnesty.org/en/documents/afr19/2708/2020/en/")],
   example="The company dug up the river and the water became bad - it made our skin itch and there was nothing left to farm on the bank.")},

"CMR": {
 3: dict(status="documented", scale=None,
   summary="THE BEST TEST CASE FOR CODE 3'S WORDING. Anglophone Cameroonians are persecuted for a LINGUISTIC and educational identity - detainees abused as 'Anglo fools', operations confined to the two Anglophone regions. This falls under 'other group membership', but a respondent scanning 'ethnic group, nationality, religion, political beliefs, sexual orientation' may not recognise themselves. Targeting also runs the other way, against francophone Bamileke traders.",
   quote=None,
   sources=[("HRW, These Killings Can Be Stopped","https://www.hrw.org/report/2018/07/19/these-killings-can-be-stopped/abuses-government-and-separatist-groups-cameroons")],
   example="We speak English and they called us names because of it. They said we were all supporting the fighters just because of where we come from and what language we speak."),
 4: dict(status="documented", scale=180000,
   summary="Security forces burned villages in the Anglophone regions - hundreds of houses at Kwakwa in January 2018, approximately 80% of Mongo Ndor in April 2018. HRW assessed 131 villages by satellite and found arson damage in 20. Over 180,000 displaced, with the UN reporting 80% hiding in the forest.",
   quote=None,
   sources=[("HRW, These Killings Can Be Stopped","https://www.hrw.org/report/2018/07/19/these-killings-can-be-stopped/abuses-government-and-separatist-groups-cameroons")],
   example="Soldiers came into the village and set fire to the houses, including my mother's. They took my son and we did not hear from him for months."),
 7: dict(status="documented", scale=300,
   summary="The village of Lolabe was destroyed for the Kribi deepwater port and its ~300 inhabitants displaced, with inadequate compensation and alleged embezzlement of the compensation fund. Nachtigal dam caused livelihood loss rather than physical displacement.",
   quote=None,
   sources=[("allAfrica on Kribi","https://allafrica.com/stories/201801100176.html"),
            ("Mongabay on Kribi","https://news.mongabay.com/2024/04/as-a-megaport-rises-in-cameroon-a-delicate-coastal-ecosystem-ebbs/")],
   example="They said our village had to go because of the new port. They gave us some money - not enough - and moved us to houses somewhere else.")},

"MLI": {
 3: dict(status="documented", scale=None,
   summary="Dozo militias attacking Fulani civilians and JNIM attacking Dogon villages - ethnic targeting running in both directions. JNIM burned 280+ homes and displaced ~2,000 people at Ogota and Ouémbé in January 2024. The 2024 law criminalising same-sex relations creates persecution risk with no documented resulting displacement.",
   quote="The Dozo targeted us because we are Fulani, and they think all Fulani are terrorists.",
   sources=[("HRW, May 2024","https://www.hrw.org/news/2024/05/08/mali-islamist-armed-groups-ethnic-militias-commit-atrocities")],
   example="The hunters came for us because we are Fulani. They said all Fulani are with the armed men, so being Fulani was enough."),
 4: dict(status="documented", scale=None,
   summary="The clearest documented case anywhere of state abuse producing anticipatory flight. Malian army and Wagner systematically executed and disappeared Fulani men across at least six documented incidents in 2025; at Sebabougou ~100 Fulani men were arrested and at least 43 bodies found near the Kwala military camp.",
   quote="We Fulani all fled because we know that the soldiers will go after us.",
   sources=[("HRW, July 2025","https://www.hrw.org/news/2025/07/22/mali-army-wagner-group-disappear-execute-fulani-civilians")],
   example="The soldiers came to the cattle market, took the men away and burned our houses. Nobody has seen the men since. We all left because we knew they would come back."),
 7: dict(status="documented", scale=12000,
   summary="Thin and dated. The Manantali dam relocated 12,000 people, but that is a 1980s-90s project - relevant only to older respondents under a lifetime-recall stem. FIDH found health and environmental harm around Sadiola and Syama gold mines but explicitly NO records of village relocations or expropriation.",
   quote=None,
   sources=[("International Rivers on Manantali","https://riverresourcehub.org/resources/a-case-study-on-the-manantali-dam-project-mali-mauritania-senegal-2011/"),
            ("FIDH, Gold Mining and Human Rights in Mali","https://www.fidh.org/IMG/pdf/Mali_mines_final-en.pdf")],
   example="When they built the dam the water covered our fields, and they moved us to a new place where the land does not produce enough.")},

"MOZ": {
 3: dict(status="documented", scale=None,
   summary="A boundary case worth noting: insurgents in at least one attack killed only civilians who presented government-issued or Frelimo identification cards. The trigger was a DOCUMENT, not an identity - which a question about the respondent's own group membership would miss. Crisis Group stresses religious language masked economic and political grievances.",
   quote=None,
   sources=[("Crisis Group, Stemming the Insurrection in Cabo Delgado","https://crisisgroup.org/sites/default/files/303-mozambique-cabo-delgado%20(1).pdf")],
   example="They stopped everyone and looked at their papers. Anyone carrying a government or party card was killed. We threw our papers away and left."),
 4: dict(status="documented", scale=None,
   summary="Security forces arbitrarily detained, ill-treated and summarily executed dozens of suspected insurgents from 2018; detainees at Chicuaia Velha described others taken into the forest followed by gunshots and screaming. Over 400 detained by July 2018, many without charge.",
   quote=None,
   sources=[("HRW, December 2018","https://www.hrw.org/news/2018/12/04/mozambique-security-forces-abusing-suspected-insurgents")],
   example="The police took the young men from our village and kept them without telling anyone. Some never came back."),
 7: dict(status="documented", scale=None,
   summary="Three distinct documented episodes: 1,429 households resettled for Tete coal mining, reporting crop failure and food insecurity; 643 households resettled for the Afungi LNG project; and thousands of artisanal miners violently expelled from the Montepuez ruby fields in early 2017 - an event Crisis Group identifies as a catalyst for the insurgency. A UK claim over the ruby fields settled for £5.8m.",
   quote="What is a house without food? I cannot eat my house.",
   sources=[("HRW on Tete resettlements","https://www.hrw.org/news/2013/05/23/mozambique-mining-resettlements-disrupt-food-water"),
            ("Crisis Group","https://crisisgroup.org/sites/default/files/303-mozambique-cabo-delgado%20(1).pdf"),
            ("Leigh Day, Gemfields case","https://www.leighday.co.uk/news/cases-and-testimonials/cases/gemfields/")],
   example="They said the gas project needed our land, so the whole village was moved to new houses further away. We can no longer reach the sea to fish.")},
}
