## =============================================================================
## 03_outputs.R - figures, dashboard, admin1 deep-dives.
## The Python prototype in prototype-python/ is the reference implementation of
## the dashboard; this reproduces the same outputs in R.
## =============================================================================

## Validated categorical palette. Only three hues are used on the choropleth
## because only codes 1, 2 and 6 ever win "dominant cause" - and three is the
## documented cap for all-pairs colourblind separation on a map.
PAL <- c("1" = "#2a78d6", "2" = "#eb6834", "6" = "#1baf7a", "none" = "#e6e5df")
STATUS_PAL <- c(RECOMMENDED = "#0ca30c", UNEVIDENCED = "#fab219",
                LOW_SALIENCE = "#e6e5df", RESIDUAL = "#2a78d6")

dominant_cause <- function(profiles) {
  profiles |>
    mutate(s = pmax(coalesce(domestic_share, 0), coalesce(origin_share, 0))) |>
    group_by(iso3) |> slice_max(s, n = 1, with_ties = FALSE) |> ungroup() |>
    transmute(iso3, dominant = if_else(s > 0, as.character(code_id), "none"), share = s)
}

make_figures <- function(profiles, evidence, idmc_detail, out) {
  dir.create(file.path(out, "figures"), showWarnings = FALSE, recursive = TRUE)

  ## Fig 1 - status of each code across all countries. The headline: code 7 is
  ## unevidenced everywhere, codes 3 and 4 nearly so.
  f1 <- profiles |> count(code_id, code_label, status) |>
    mutate(code_label = factor(paste0(code_id, ". ", code_label))) |>
    ggplot(aes(n, reorder(code_label, -code_id), fill = status)) +
    geom_col(width = .62) +
    scale_fill_manual(values = STATUS_PAL, name = NULL) +
    labs(x = "Countries", y = NULL,
         title = "Evidence status of each response option, by country",
         subtitle = "Codes 3, 4 and 7 are where global data is structurally blind") +
    theme_minimal(base_size = 11) +
    theme(panel.grid.major.y = element_blank(), legend.position = "top")
  ggsave(file.path(out, "figures", "fig1_status_by_code.png"), f1,
         width = 9, height = 4.2, dpi = 200)

  ## Fig 2 - domestic vs origin-weighted evidence for code 1. Points far above
  ## the diagonal are countries whose showcard is driven by refugees' origins.
  f2 <- profiles |> filter(code_id == 1, refugees_hosted > 5000) |>
    ggplot(aes(coalesce(domestic_share, 0), origin_share)) +
    geom_abline(linetype = 2, colour = "#898781") +
    geom_point(aes(size = refugees_hosted), alpha = .7, colour = PAL[["1"]]) +
    scale_size_area(max_size = 9, labels = scales::comma, name = "Refugees hosted") +
    scale_x_continuous(labels = scales::percent) +
    scale_y_continuous(labels = scales::percent) +
    labs(x = "Share of the country's own displacement caused by armed conflict",
         y = "Origin-weighted share (refugees hosted)",
         title = "Where the case for 'armed conflict' rests on refugees' origins",
         subtitle = "Above the diagonal: local events would not justify the option; the hosted population does") +
    theme_minimal(base_size = 11)
  ggsave(file.path(out, "figures", "fig2_domestic_vs_origin.png"), f2,
         width = 8, height = 5.6, dpi = 200)

  ## Fig 3 - hazard subtype mix for the largest disaster-displacement contexts.
  ## This is the raw material for country-specific enumerator examples of code 6.
  top <- idmc_detail |> filter(code_id == 6, category == "Internal Displacements") |>
    group_by(iso3) |> summarise(v = sum(figures, na.rm = TRUE)) |>
    slice_max(v, n = 15) |> pull(iso3)
  f3 <- idmc_detail |>
    filter(code_id == 6, category == "Internal Displacements", iso3 %in% top) |>
    group_by(iso3, hazard_type) |>
    summarise(v = sum(figures, na.rm = TRUE), .groups = "drop") |>
    ggplot(aes(v, reorder(iso3, v), fill = hazard_type)) +
    geom_col(width = .68) +
    scale_x_continuous(labels = scales::comma) +
    labs(x = "People displaced", y = NULL, fill = NULL,
         title = "Hazard mix behind code 6, largest disaster-displacement contexts",
         subtitle = "Determines which examples the enumerator screen should give locally") +
    theme_minimal(base_size = 11) + theme(panel.grid.major.y = element_blank())
  ggsave(file.path(out, "figures", "fig3_hazard_mix.png"), f3,
         width = 9, height = 6, dpi = 200)

  invisible(list(f1, f2, f3))
}

make_dashboard <- function(profiles, evidence, idmc_detail, population, out) {
  ## The reference dashboard is generated by prototype-python/build_dashboard.py,
  ## which embeds world-atlas geometry and the profiles as inline JSON in a
  ## single self-contained HTML file. Reproduce in R with:
  ##   jsonlite::toJSON() the profiles + an sf world layer, then whisker/glue
  ##   into the same template. Kept out of the critical path so the R pipeline
  ##   does not depend on a map package being installed.
  message("dashboard: run prototype-python/build_dashboard.py, ",
          "or port the template - see README")
  invisible(NULL)
}

make_admin1_profiles <- function(evidence, idmc_detail, isos, out) {
  ## Subnational layer. ACLED aggregated already carries ADMIN1; IDMC IDU rows
  ## carry coordinates plus a Locations accuracy field indicating ADM1/2/3.
  a <- evidence |>
    filter(iso3 %in% isos, !is.na(admin1), evidence_type == "events") |>
    group_by(iso3, admin1, code_id) |>
    summarise(events = sum(value), .groups = "drop") |>
    group_by(iso3, admin1) |> mutate(share = events / sum(events)) |> ungroup()
  if (!nrow(a)) {
    message("no admin1 evidence for the requested countries - ",
            "add the ACLED regional exports that cover them")
    return(invisible(NULL))
  }
  readr::write_csv(a, file.path(out, "admin1_cause_profiles.csv"))
  message("admin1 profiles: ", nrow(a), " rows -> admin1_cause_profiles.csv")
  invisible(a)
}
